name: Build Examples

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ '**.md' ]

jobs:
  build:
    runs-on: macos-latest
    env:
      CFLAGS: -Werror=deprecated-declarations
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: >
        cmake
        -D GLFM_BUILD_EXAMPLES=ON
        -D CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY=""
        -D CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED=NO
        -B build/apple_examples
        -G Xcode

    - name: Build
      run: cmake --build build/apple_examples
